/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Videos', [
      {
        uploadedBy: 1,
        title: 'React за 100 секунд',
        description: 'Быстрый обзор основных концепций React для начинающих',
        duration: 120,
        size: 104857600,
        year: 2024,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'openings',
        isPublic: true,
        viewsCount: 100,
      },
      {
        uploadedBy: 2,
        title: 'Оптимизация PostgreSQL запросов',
        description: 'Практические советы по ускорению работы с базой данных',
        duration: 600,
        size: 524288000,
        year: 2024,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'Openings',
        isPublic: true,
        viewsCount: 150,
      },
      {
        uploadedBy: 3,
        title: 'Тренды дизайна 2024',
        description: 'Обзор современных трендов в UI/UX дизайне',
        duration: 450,
        size: 314572800,
        year: 2024,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'openings',
        isPublic: false,
        viewsCount: 200,
      },
      {
        uploadedBy: 4,
        title: 'Длинное название видео',
        description: 'Короткометражный анимационный фильм',
        duration: 596,
        size: 104857600,
        year: 2008,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'movie',
        isPublic: true,
        viewsCount: 50,
      },
      {
        uploadedBy: 5,
        title: 'Сон слонёнка',
        description:
          'Первый открытый фильм о слонёнке, который мечтает стать слонёнком и обрести свободу.',
        duration: 600,
        size: 157286400,
        year: 2006,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'movie',
        isPublic: true,
        viewsCount: 60,
      },
      {
        uploadedBy: 6,
        title: 'Крупные пожары в России',
        description: 'Обзор крупных пожаров в России за последние годы',
        duration: 15,
        size: 2684354,
        year: 2016,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'openings',
        isPublic: true,
        viewsCount: 70,
      },
      {
        uploadedBy: 7,
        title: 'Захватывающие путешествия по России',
        description: 'Обзор захватывающих путешествий по России',
        duration: 15,
        size: 3678901,
        year: 2016,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'openings',
        isPublic: false,
        viewsCount: 80,
      },
      {
        uploadedBy: 8,
        title: 'Суперкары на улицах и в лесу',
        description: 'Обзор Subaru Outback',
        duration: 180,
        size: 12345678,
        year: 2016,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'travel',
        isPublic: true,
        viewsCount: 90,
      },
      {
        uploadedBy: 9,
        title: 'Тени стали',
        description:
          'Короткометражный фильм о стали, которая стала жить и дышать.',
        duration: 734,
        size: 25678901,
        year: 2012,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'movie',
        isPublic: true,
        viewsCount: 100,
      },
      {
        uploadedBy: 10,
        title: 'Живая сталь',
        description: 'Короткометражный фильм.',
        duration: 888,
        size: 31457280,
        year: 2010,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'movie',
        isPublic: true,
        viewsCount: 110,
      },
      {
        uploadedBy: 11,
        title: 'Мы едем на буллрэн',
        description: 'Экстремальное вождение',
        duration: 164,
        size: 9876543,
        year: 2016,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'sports',
        isPublic: true,
        viewsCount: 120,
      },
      {
        uploadedBy: 12,
        title: 'Что такое WebM?',
        description: 'Объяснение формата WebM',
        duration: 48,
        size: 567890,
        year: 2026,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'openings',
        isPublic: false,
        viewsCount: 130,
      },
      {
        uploadedBy: 8,
        title: 'Бег по горам в Альпах',
        description: 'Трейлраннинг в Альпах',
        duration: 420,
        size: 29360128,
        year: 2026,
        videoUrl: '/default-video.mp4',
        thumbnailUrl: '/default-image.jpg',
        previewUrl: '/default-preview.mp4',
        category: 'sports',
        isPublic: false,
        viewsCount: 140,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Videos', null, {});
  },
};
