/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Users', [
      {
        nickname: 'alex_92',
        name: 'Алексей Иванов',
        birthDate: '1992-04-06',
        email: 'alex92@example.com',
        address: 'Москва, м. Бауманская',
        job: 'Frontend Developer',
        status: 'Через тернии к звёздам',
        phone: '+7 (916) 123-45-67',
        avatarUrl: null,
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'maria_joy',
        name: 'Мария Петрова',
        birthDate: '1997-05-18',
        email: 'maria@example.com',
        address: 'Санкт-Петербург, м. Невский проспект',
        job: 'Designer UI/UX',
        status: 'Люблю создавать красивые и удобные интерфейсы',
        phone: '+7 (916) 765-43-21',
        avatarUrl: null,
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'tech_guru',
        name: 'Дмитрий Сидоров',
        birthDate: '1987-11-20',
        email: 'dmitry@example.com',
        address: 'Казань, м. Казанская',
        job: 'Backend Developer',
        status: 'Пишу на Node.js, Python и Go',
        phone: '+7 (916) 555-77-88',
        avatarUrl: null,
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'ivan_petrov',
        name: 'Иван Петров',
        birthDate: '1989-03-10',
        email: 'ivan.petrov@mail.ru',
        address: 'Москва, м. Новослободская',
        job: 'Каменщик',
        status: 'Строю дом своей мечты',
        phone: '+7 (953) 678-88-32',
        avatarUrl: null,
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'veronika_sid',
        name: 'Вероника Сидорова',
        birthDate: '1994-07-25',
        email: 'veronika.sidorova@gmail.com',
        address: 'Санкт-Петербург, м. Площадь Ленина',
        job: 'Фотограф',
        status: 'Я люблю фотографировать птиц',
        phone: '+7 (911) 234-56-78',
        avatarUrl: null,
        isPublic: false,
        gender: 'female',
        passwordHash: 123,
      },

      {
        nickname: 'sergey_pro',
        name: 'Сергей Прохоров',
        birthDate: '1987-11-28',
        email: 'sergey.prokhorov@yandex.ru',
        address: 'Новосибирск, м. Березовая Роща',
        job: 'Водитель',
        status: 'Нахожусь в поиске новой работы',
        phone: '+7 (913) 456-78-90',
        avatarUrl: null,
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'ekaterina_kuz',
        name: 'Екатерина Кузнецова',
        birthDate: '1993-04-12',
        email: 'ekaterina.kuznetsova@bk.ru',
        address: 'Екатеринбург, Площадь 1905 года, 89',
        job: 'Дизайнер',
        status: 'Люблю путешествовать и фотографировать',
        phone: '+7 (912) 345-67-89',
        avatarUrl: null,
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'jovinco',
        name: 'Олег Малахов',
        birthDate: '1987-06-15',
        email: 'malahov.1987@mail.ru',
        address: 'Смоленск, пр-т Строителей',
        job: 'Full stack developer',
        status: 'В поиске новых вызовов',
        phone: '+7 (915) 654-88-42',
        avatarUrl: null,
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'dmitriy_smir',
        name: 'Андрей Смирнов',
        birthDate: '1991-06-18',
        email: 'dmitriy.smirnov@inbox.ru',
        address: 'Казань, м. Кремлёвская',
        job: 'Барбер',
        status: 'Приглашаю всех к нам в барбершоп!',
        phone: '+7 (987) 654-32-10',
        avatarUrl: null,
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'anna_mac',
        name: 'Анна Макарова',
        birthDate: '1998-09-22',
        email: 'anya.makarova@gmail.com',
        address: 'Сочи, мкр-н Адлер',
        job: 'Администратор',
        status: 'Скоро выхожу замуж! Ура!',
        phone: '+7 (916) 455-76-98',
        avatarUrl: null,
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'sofia_f',
        name: 'Софья Филимонова',
        birthDate: '1986-03-08',
        email: 'sofia_fill@gmail.com',
        address: 'Смоленск, ул. Румянцева',
        job: 'Домохозяйка',
        status: 'В активном поиске хорошего мужа!',
        phone: '+7 (915) 985-32-21',
        avatarUrl: null,
        isPublic: false,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'artem_v',
        name: 'Артём Волков',
        birthDate: '1992-07-15',
        email: 'artem.volkov@yandex.ru',
        address: 'Ростов-на-Дону, ул. Ленина',
        job: 'Системный администратор',
        status: 'Обожаю программировать, когда у меня есть свободное время!',
        phone: '+7 (919) 567-89-01',
        avatarUrl: null,
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'elena_n',
        name: 'Елена Новикова',
        birthDate: '1995-01-01',
        email: 'elena.novikova@mail.ru',
        address: 'Уфа, ул. Гоголя',
        job: 'Повар',
        status: 'Люблю готовить и пишу книгу о кулинарии',
        phone: '+7 (910) 234-56-78',
        avatarUrl: null,
        isPublic: false,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'igor_k',
        name: 'Игорь Ковалёв',
        birthDate: '1990-05-05',
        email: 'igor.kovalyov@inbox.ru',
        address: 'Пермь, ул. Ленина',
        job: 'Строитель',
        status: 'На отдыхе в горах',
        phone: '+7 (917) 890-12-34',
        avatarUrl: null,
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'vera_m',
        name: 'Вера Морозова',
        birthDate: '1996-03-15',
        email: 'vera.morozova@gmail.com',
        address: 'Чита, ул. Советская',
        job: 'Юрист',
        status: 'Свободна для работы',
        phone: '+7 (918) 789-01-23',
        avatarUrl: null,
        isPublic: false,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'alexandra_b',
        name: 'Александра Белова',
        birthDate: '1997-07-20',
        email: 'alexandra.belova@bk.ru',
        address: 'Тула, ул. Пушкина',
        job: 'Модель',
        status: 'Снимаю ролики для TikTok',
        phone: '+7 (914) 567-89-01',
        avatarUrl: null,
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'mikhail_y',
        name: 'Михаил Яковлев',
        birthDate: '1988-11-10',
        email: 'mikhail.yakovlev@yandex.ru',
        address: 'Краснодар, ул. Ленина',
        job: 'Преподаватель',
        status: 'Изучаю новые языки программирования',
        phone: '+7 (913) 556-78-90',
        avatarUrl: null,
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'anastasia_s',
        name: 'Анастасия Соколова',
        birthDate: '1999-04-08',
        email: 'anastasia.sokolova@gmail.com',
        address: 'Владивосток, ул. Ленина',
        job: 'Медицинская сестра',
        status: 'Сегодня день рождения!',
        phone: '+7 (912) 375-67-89',
        avatarUrl: null,
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
