/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Videos', [
      {
        uploadedBy: 1,
        title: 'React за 100 секунд',
        description: 'Быстрый обзор основных концепций React для начинающих',
        duration: 120,
        size: 104857600,
        year: 2024,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Openings',
        isPublic: true,
        viewsCount: 30,
      },
      {
        uploadedBy: 2,
        title: 'Оптимизация PostgreSQL запросов',
        description: 'Практические советы по ускорению работы с базой данных',
        duration: 600,
        size: 524288000,
        year: 2024,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Openings',
        isPublic: true,
        viewsCount: 20,
      },
      {
        uploadedBy: 3,
        title: 'Тренды дизайна 2024',
        description: 'Обзор современных трендов в UI/UX дизайне',
        duration: 450,
        size: 314572800,
        year: 2024,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Openings',
        isPublic: false,
        viewsCount: 10,
      },
      {
        uploadedBy: 4,
        title: 'Big Buck Bunny',
        description: 'Короткометражный анимационный фильм',
        duration: 596,
        size: 104857600,
        year: 2008,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Movie',
        isPublic: true,
        viewsCount: 5,
      },
      {
        uploadedBy: 5,
        title: 'Elephant Dream',
        description: 'Первый открытый фильм Blender Foundation',
        duration: 600,
        size: 157286400,
        year: 2006,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Movie',
        isPublic: true,
        viewsCount: 35,
      },
      {
        uploadedBy: 6,
        title: 'For Bigger Blazes',
        description: 'Рекламный ролик H.264',
        duration: 15,
        size: 2684354,
        year: 2016,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Openings',
        isPublic: true,
        viewsCount: 25,
      },
      {
        uploadedBy: 7,
        title: 'For Bigger Joyrides',
        description: 'Ещё один демо-ролик',
        duration: 15,
        size: 3678901,
        year: 2016,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Openings',
        isPublic: false,
        viewsCount: 10,
      },
      {
        uploadedBy: 8,
        title: 'Subaru Outback On Street And Dirt',
        description: 'Обзор Subaru Outback',
        duration: 180,
        size: 12345678,
        year: 2016,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Travel',
        isPublic: true,
        viewsCount: 15,
      },
      {
        uploadedBy: 9,
        title: 'Tears of Steel',
        description: 'Короткометражный фильм Blender Foundation',
        duration: 734,
        size: 25678901,
        year: 2012,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Movie',
        isPublic: true,
        viewsCount: 10,
      },
      {
        uploadedBy: 10,
        title: 'Sintel',
        description: 'Короткометражный фильм Blender Foundation',
        duration: 888,
        size: 31457280,
        year: 2010,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Movie',
        isPublic: true,
        viewsCount: 100,
      },
      {
        uploadedBy: 11,
        title: 'We Are Going On Bullrun',
        description: 'Экстремальное вождение',
        duration: 164,
        size: 9876543,
        year: 2016,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Sports',
        isPublic: true,
        viewsCount: 60,
      },
      {
        uploadedBy: 12,
        title: 'What is WebM?',
        description: 'Объяснение формата WebM',
        duration: 48,
        size: 567890,
        year: 2026,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Openings',
        isPublic: false,
        viewsCount: 40,
      },
      {
        uploadedBy: 8,
        title: 'Бег по горам',
        description: 'Трейлраннинг в Альпах',
        duration: 420,
        size: 29360128,
        year: 2026,
        url: '/default-video.mp4',
        thumbnail: '/default-thumbnail.mp4',
        category: 'Sports',
        isPublic: false,
        viewsCount: 20,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Videos', null, {});
  },
};
