/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Posts', [
      {
        userId: 1,
        text: 'Сегодня завершил большой проект! Очень доволен результатом.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 2,
        text: 'Ищу вдохновение для нового дизайна.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 3,
        text: 'Поделюсь кодом оптимизации запросов к PostgreSQL.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 4,
        text: 'Можете меня поздравить, это было нечто. Я выучил JavaScript за 10 минут.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 5,
        text: 'Основные материалы для изучения JavaScript: https://doka.guide',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 6,
        text: 'Сколько стоит обучение в школе программирования на JavaScript?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 7,
        text: 'Обучающее видео: как я выучил JavaScript за 10 минут.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 8,
        text: 'Красивое фото из Грузии.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 9,
        text: 'Мое первое фото из Швейцарии.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 10,
        text: 'Поздравьте меня с днем рождения! Сегодня отличная погода.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 11,
        text: 'Я выучила React и устроилась на работу. Теперь я работаю 24/7.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 12,
        text: 'Основные материалы для изучения JavaScript: https://doka.guide/js',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 13,
        text: 'Видео с уроком по PostgreSQL.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 14,
        text: 'Фото из путешествия в Тайланд.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 15,
        text: 'Ребята продают машину в отличном состоянии.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'image',
        pinned: false,
        isEdited: false,
      },

      {
        userId: 16,
        text: 'Основные материалы для изучения JavaScript: https://doka.guide/js/expressions-vs-statements',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 17,
        text: 'Сегодня изучаем Redux Toolkit.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 18,
        text: 'Когда же это уже все закончится?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 1,
        text: 'Какой сегодня чудесный день! Выходные!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 2,
        text: 'Какой сериал посоветуете посмотреть?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 3,
        text: 'Поздравляю всех с началом лета! Оно будет прекрасным.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 4,
        text: 'Поздравляю Вас с прошедшими майскими праздниками! Всем добра и мира!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 5,
        text: 'Скоро отпуск! Ура! Уже взяли билеты в Сочи! Красная Поляна ждет нас.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 6,
        text: 'Пора бы уже и мне найти работу. Ребята как у Вас сейчас дела с работой?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 7,
        text: 'Сегодня освоен React Router. Завтра начну изучать Redux и так выучу React.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 8,
        text: 'Скоро мое первое путешествие в Японию!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 9,
        text: 'Учимся программировать. Подписываемся на мой канал в YouTube и Telegram!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Posts', null, {});
  },
};
