/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Videos', [
      {
        uploadedBy: 1,
        title: 'React за 100 секунд',
        description: 'Быстрый обзор основных концепций React для начинающих',
        duration: 120,
        size: 104857600,
        year: 2024,
        videoUrl: 'https://www.w3schools.com/html/movie.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=5',
        category: 'Openings',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 2,
        title: 'Оптимизация PostgreSQL запросов',
        description: 'Практические советы по ускорению работы с базой данных',
        duration: 600,
        size: 524288000,
        year: 2024,
        videoUrl: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=6',
        category: 'Openings',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 3,
        title: 'Тренды дизайна 2024',
        description: 'Обзор современных трендов в UI/UX дизайне',
        duration: 450,
        size: 314572800,
        year: 2024,
        videoUrl: 'https://samplelib.com/mp4/sample-10s.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=7',
        category: 'Openings',
        isPublic: false,
        viewCount: 0,
      },
      {
        uploadedBy: 4,
        title: 'Big Buck Bunny',
        description: 'Короткометражный анимационный фильм',
        duration: 596,
        size: 104857600,
        year: 2008,
        videoUrl: 'https://www.w3schools.com/html/movie.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=8',
        category: 'Movie',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 5,
        title: 'Elephant Dream',
        description: 'Первый открытый фильм Blender Foundation',
        duration: 600,
        size: 157286400,
        year: 2006,
        videoUrl: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=9',
        category: 'Movie',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 6,
        title: 'For Bigger Blazes',
        description: 'Рекламный ролик H.264',
        duration: 15,
        size: 2684354,
        year: 2016,
        videoUrl: 'http://vjs.zencdn.net/v/oceans.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=10',
        category: 'Openings',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 7,
        title: 'For Bigger Joyrides',
        description: 'Ещё один демо-ролик',
        duration: 15,
        size: 3678901,
        year: 2016,
        videoUrl: 'https://samplelib.com/mp4/sample-10s.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=11',
        category: 'Openings',
        isPublic: false,
        viewCount: 0,
      },
      {
        uploadedBy: 8,
        title: 'Subaru Outback On Street And Dirt',
        description: 'Обзор Subaru Outback',
        duration: 180,
        size: 12345678,
        year: 2016,
        videoUrl:
          'https://test-videos.co.uk/vids/jellyfish/mp4/h264/1080/Jellyfish_1080_10s_1MB.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=12',
        category: 'Travel',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 9,
        title: 'Tears of Steel',
        description: 'Короткометражный фильм Blender Foundation',
        duration: 734,
        size: 25678901,
        year: 2012,
        videoUrl:
          'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=13',
        category: 'Movie',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 10,
        title: 'Sintel',
        description: 'Короткометражный фильм Blender Foundation',
        duration: 888,
        size: 31457280,
        year: 2010,
        videoUrl: 'https://test-videos.co.uk/vids/sintel/mp4/av1/1080/Sintel_1080_10s_1MB.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=17',
        category: 'Movie',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 11,
        title: 'We Are Going On Bullrun',
        description: 'Экстремальное вождение',
        duration: 164,
        size: 9876543,
        year: 2016,
        videoUrl:
          'https://test-videos.co.uk/vids/jellyfish/mp4/h264/1080/Jellyfish_1080_10s_1MB.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=18',
        category: 'Sports',
        isPublic: true,
        viewCount: 0,
      },
      {
        uploadedBy: 12,
        title: 'What is WebM?',
        description: 'Объяснение формата WebM',
        duration: 48,
        size: 567890,
        year: 2026,
        videoUrl:
          'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatIsWebM.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=19',
        category: 'Openings',
        isPublic: false,
        viewCount: 0,
      },
      {
        uploadedBy: 13,
        title: 'Бег по горам',
        description: 'Трейлраннинг в Альпах',
        duration: 420,
        size: 29360128,
        year: 2026,
        videoUrl: 'https://storage.example.com/videos/trail-running.mp4',
        thumbnailUrl: 'https://picsum.photos/320/180?random=24',
        category: 'Sports',
        isPublic: false,
        viewCount: 0,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Videos', null, {});
  },
};
