/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    // Дружеские связи
    await queryInterface.bulkInsert('Friends', [
      { userId: 1, friendId: 2, status: 'accepted' },
      { userId: 1, friendId: 3, status: 'accepted' },
      { userId: 2, friendId: 3, status: 'pending' },
      { userId: 1, friendId: 8, status: 'blocked' },
      { userId: 8, friendId: 2, status: 'accepted' },
      { userId: 3, friendId: 8, status: 'pending' },
      { userId: 8, friendId: 4, status: 'accepted' },
      { userId: 5, friendId: 8, status: 'accepted' },
      { userId: 6, friendId: 3, status: 'accepted' },
      { userId: 7, friendId: 8, status: 'accepted' },
      { userId: 11, friendId: 9, status: 'accepted' },
      { userId: 10, friendId: 9, status: 'accepted' },
      { userId: 10, friendId: 11, status: 'accepted' },
      { userId: 11, friendId: 5, status: 'pending' },
      { userId: 2, friendId: 10, status: 'accepted' },
      { userId: 5, friendId: 9, status: 'accepted' },
      { userId: 4, friendId: 10, status: 'blocked' },
      { userId: 6, friendId: 10, status: 'pending' },
      { userId: 8, friendId: 11, status: 'blocked' },
      { userId: 8, friendId: 6, status: 'pending' },
    ]);

    // Лайки
    await queryInterface.bulkInsert('Likes', [
      { userId: 1, targetType: 'Post', targetId: 1 },
      { userId: 2, targetType: 'Post', targetId: 2 },
      { userId: 3, targetType: 'Post', targetId: 3 },
      { userId: 4, targetType: 'Post', targetId: 4 },
      { userId: 5, targetType: 'Post', targetId: 5 },
      { userId: 6, targetType: 'Post', targetId: 6 },
      { userId: 7, targetType: 'Post', targetId: 7 },
      { userId: 8, targetType: 'Post', targetId: 8 },
      { userId: 9, targetType: 'Post', targetId: 9 },
      { userId: 10, targetType: 'Post', targetId: 10 },
      { userId: 1, targetType: 'News', targetId: 1 },
      { userId: 2, targetType: 'News', targetId: 2 },
      { userId: 3, targetType: 'News', targetId: 3 },
      { userId: 4, targetType: 'News', targetId: 4 },
      { userId: 5, targetType: 'News', targetId: 5 },
      { userId: 6, targetType: 'News', targetId: 6 },
      { userId: 7, targetType: 'News', targetId: 7 },
      { userId: 8, targetType: 'News', targetId: 8 },
      { userId: 9, targetType: 'News', targetId: 9 },
      { userId: 10, targetType: 'News', targetId: 10 },
      { userId: 1, targetType: 'Music', targetId: 1 },
      { userId: 2, targetType: 'Music', targetId: 2 },
      { userId: 3, targetType: 'Music', targetId: 3 },
      { userId: 4, targetType: 'Music', targetId: 4 },
      { userId: 5, targetType: 'Music', targetId: 5 },
      { userId: 6, targetType: 'Music', targetId: 6 },
      { userId: 7, targetType: 'Music', targetId: 7 },
      { userId: 8, targetType: 'Music', targetId: 8 },
      { userId: 9, targetType: 'Music', targetId: 9 },
      { userId: 10, targetType: 'Music', targetId: 10 },
      { userId: 1, targetType: 'Video', targetId: 1 },
      { userId: 2, targetType: 'Video', targetId: 2 },
      { userId: 3, targetType: 'Video', targetId: 3 },
      { userId: 4, targetType: 'Video', targetId: 4 },
      { userId: 5, targetType: 'Video', targetId: 5 },
      { userId: 6, targetType: 'Video', targetId: 6 },
      { userId: 7, targetType: 'Video', targetId: 7 },
      { userId: 8, targetType: 'Video', targetId: 8 },
      { userId: 9, targetType: 'Video', targetId: 9 },
      { userId: 10, targetType: 'Video', targetId: 10 },
      { userId: 1, targetType: 'Comment', targetId: 1 },
      { userId: 2, targetType: 'Comment', targetId: 2 },
      { userId: 3, targetType: 'Comment', targetId: 3 },
      { userId: 4, targetType: 'Comment', targetId: 4 },
      { userId: 5, targetType: 'Comment', targetId: 5 },
      { userId: 6, targetType: 'Comment', targetId: 6 },
      { userId: 7, targetType: 'Comment', targetId: 7 },
      { userId: 8, targetType: 'Comment', targetId: 8 },
      { userId: 9, targetType: 'Comment', targetId: 9 },
      { userId: 10, targetType: 'Comment', targetId: 10 },
      { userId: 11, targetType: 'Comment', targetId: 11 },
      { userId: 12, targetType: 'Comment', targetId: 12 },
    ]);

    // Комментарии
    await queryInterface.bulkInsert('Comments', [
      {
        userId: 1,
        targetType: 'Post',
        targetId: 1,
        text: 'Это интересно!',
      },
      {
        userId: 2,
        targetType: 'Post',
        targetId: 2,
        text: 'Очень полезный пост!',
      },
      {
        userId: 3,
        targetType: 'Post',
        targetId: 3,
        text: 'Можно подробнее!',
      },
      {
        userId: 4,
        targetType: 'Post',
        targetId: 4,
        text: 'Спасибо за информацию!',
      },
      {
        userId: 5,
        targetType: 'Post',
        targetId: 5,
        text: 'Очень полезная статья!',
      },
      {
        userId: 6,
        targetType: 'Post',
        targetId: 6,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 7,
        targetType: 'Post',
        targetId: 7,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 8,
        targetType: 'Post',
        targetId: 8,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 9,
        targetType: 'Post',
        targetId: 9,
        text: 'Это интересно!',
      },
      {
        userId: 10,
        targetType: 'Post',
        targetId: 10,
        text: 'Очень полезная новость!',
      },
      {
        userId: 11,
        targetType: 'Post',
        targetId: 11,
        text: 'Очень полезный пост!',
      },
      {
        userId: 12,
        targetType: 'Post',
        targetId: 12,
        text: 'Это интересно!',
      },
      {
        userId: 1,
        targetType: 'News',
        targetId: 1,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 2,
        targetType: 'News',
        targetId: 2,
        text: 'Спасибо за материал!',
      },
      {
        userId: 3,
        targetType: 'News',
        targetId: 3,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 4,
        targetType: 'News',
        targetId: 4,
        text: 'Это интересно!',
      },
      {
        userId: 5,
        targetType: 'News',
        targetId: 5,
        text: 'Мне очень понравилось!',
      },
      {
        userId: 6,
        targetType: 'News',
        targetId: 6,
        text: 'Интересный материал!',
      },
      {
        userId: 7,
        targetType: 'News',
        targetId: 7,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 8,
        targetType: 'News',
        targetId: 8,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 9,
        targetType: 'News',
        targetId: 9,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 10,
        targetType: 'News',
        targetId: 10,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 11,
        targetType: 'News',
        targetId: 11,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 12,
        targetType: 'News',
        targetId: 12,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 1,
        targetType: 'Video',
        targetId: 1,
        text: 'Красивое видео!',
      },
      {
        userId: 2,
        targetType: 'Video',
        targetId: 2,
        text: 'Очень хорошее видео!',
      },
      {
        userId: 3,
        targetType: 'Video',
        targetId: 3,
        text: 'Очень хорошее видео!',
      },
      {
        userId: 4,
        targetType: 'Video',
        targetId: 4,
        text: 'Красивое видео!',
      },
      {
        userId: 5,
        targetType: 'Video',
        targetId: 5,
        text: 'Очень хорошее видео!',
      },
      {
        userId: 6,
        targetType: 'Video',
        targetId: 6,
        text: 'Классное видео!',
      },
      {
        userId: 7,
        targetType: 'Video',
        targetId: 7,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 8,
        targetType: 'Video',
        targetId: 8,
        text: 'Классное видео! Спасибо за подробную информацию!',
      },
      {
        userId: 9,
        targetType: 'Video',
        targetId: 9,
        text: 'Очень хорошее видео!',
      },
      {
        userId: 10,
        targetType: 'Video',
        targetId: 10,
        text: 'Очень хорошее видео!',
      },
      {
        userId: 1,
        targetType: 'Music',
        targetId: 1,
        text: 'Красивая песня!',
      },
      {
        userId: 2,
        targetType: 'Music',
        targetId: 2,
        text: 'Очень хорошая песня!',
      },
      {
        userId: 3,
        targetType: 'Music',
        targetId: 3,
        text: 'Очень хорошая песня!',
      },
      {
        userId: 4,
        targetType: 'Music',
        targetId: 4,
        text: 'Красивая песня!',
      },
      {
        userId: 5,
        targetType: 'Music',
        targetId: 5,
        text: 'Очень хорошая песня!',
      },
      {
        userId: 6,
        targetType: 'Music',
        targetId: 6,
        text: 'Классная песня!',
      },
      {
        userId: 7,
        targetType: 'Music',
        targetId: 7,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 8,
        targetType: 'Music',
        targetId: 8,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 9,
        targetType: 'Music',
        targetId: 9,
        text: 'Спасибо за подробную информацию!',
      },
      {
        userId: 10,
        targetType: 'Music',
        targetId: 10,
        text: 'Спасибо за подробную информацию!',
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Comments', null, {});
    await queryInterface.bulkDelete('Likes', null, {});
    await queryInterface.bulkDelete('Friends', null, {});
  },
};
