/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('News', [
      {
        uploadedBy: 13,
        title: 'Новый фреймворк React 19 выходит в этом году',
        text: 'Команда Facebook анонсировала выход React 19 с новыми функциями. Этот фреймворк позволяет создавать веб-приложения с использованием JavaScript и React.',
        category: 'technology',
        type: 'image',
        source: 'Комсомольская правда',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 10,
        isEdited: false,
      },
      {
        uploadedBy: 12,
        title: 'ИИ создает музыку неотличимую от человеческой',
        text: 'Нейросети GPT-4 научились генерировать музыкальные композиции. Этот ИИ позволяет создавать музыкальные композиции с использованием нейросетей.',
        category: 'technology',
        type: 'text',
        source: '7 дней',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 15,
        isEdited: false,
      },
      {
        uploadedBy: 11,
        title: 'Новые технологии в медицине',
        text: 'Ученые разработали революционный метод лечения онкологических заболеваний с использованием нанороботов. Этот метод позволяет лечить онкологические заболевания с использованием нанороботов.',
        category: 'technology',
        type: 'text',
        source: 'Медицинский эксперт',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 20,
        isEdited: false,
      },
      {
        uploadedBy: 4,
        title: 'Изменения в налоговом законодательстве',
        text: 'С нового года вступают в силу поправки, предусматривающие льготы для малого и среднего бизнеса. Эти поправки позволяют малому и среднему бизнесу получать льготы и субсидии от государства.',
        category: 'economy',
        type: 'video',
        source: 'Экономический обозреватель',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 25,
        isEdited: false,
      },
      {
        uploadedBy: 5,
        title: 'Климатический саммит в Париже',
        text: 'Лидеры стран договорились о сокращении выбросов углекислого газа на 30% к 2030 году. Это позволит странам достичь целей по сокращению выбросов углекислого газа на 30% к 2030 году. ',
        category: 'health',
        type: 'image',
        source: 'Экологический корреспондент',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 30,
        isEdited: false,
      },
      {
        uploadedBy: 6,
        title: 'Открытие нового культурного центра',
        text: 'В центре Москвы открылся современный арт-пространство с выставочными залами и мастерскими. Этот центр позволяет людям познакомиться с современным искусством и культурой.',
        category: 'culture',
        type: 'text',
        source: 'Культурный обозреватель',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 35,
        isEdited: false,
      },
      {
        uploadedBy: 7,
        title: 'Прорыв в космической отрасли',
        text: 'Частная компания успешно запустила многоразовую ракету для доставки грузов на орбиту. Этот шаг позволит компаниям доставлять грузы на орбиту с использованием многоразовых ракет.',
        category: 'technology',
        type: 'video',
        source: 'Космический аналитик',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 40,
        isEdited: false,
      },
      {
        uploadedBy: 8,
        title: 'Российские теннисисты вышли в финал Кубка Дэвиса',
        text: 'Сборная России по теннису обыграла команду Германии со счетом 3-1 в полуфинале Кубка Дэвиса. Решающее очко принес Даниил Медведев, обыгравший Александра Зверева. В финале россияне встретятся с действующими чемпионами - сборной Италии. Этот успех позволит россиянам занять лидирующие позиции в теннисе.',
        category: 'sports',
        type: 'text',
        source: 'Спорт экспресс',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 45,
        isEdited: false,
      },
      {
        uploadedBy: 9,
        title: 'Сборная России по футболу снова вылетела из чемпионата Европы',
        text: 'Сборная России вылетела из чемпионата Европы по футболу проиграв сборной Греции со счетом 1:6. По итогу команда сборной России не выиграла ни одного матча на чемпионате. Главный тренер все вину взял на себя. Этот результат позволит россиянам занять последние места в чемпионате Европы по футболу.',
        category: 'sports',
        type: 'text',
        source: 'Новости спорта',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 50,
        isEdited: false,
      },
      {
        uploadedBy: 10,
        title: 'SpaceX успешно запустила Starship в пятый испытательный полет',
        text: 'Компания Илона Маска SpaceX провела пятый испытательный запуск космического корабля Starship. В отличие от предыдущих попыток, прототип успешно совершил мягкую посадку в Индийском океане. Это открывает новые перспективы для лунной программы NASA и будущих миссий на Марс.',
        category: 'technology',
        type: 'text',
        source: 'IT индустрия',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 15,
        isEdited: false,
      },
      {
        uploadedBy: 14,
        title: 'Рубль укрепился после переговоров по нефти',
        text: 'Российская валюта показала рост на 2.5% по отношению к доллару после успешных переговоров стран ОПЕК+. Эксперты связывают укрепление с договоренностью о сокращении добычи нефти и стабилизацией цен на энергоносители. Аналитики прогнозируют сохранение тренда в ближайшие месяцы.',
        category: 'economy',
        type: 'image',
        source: 'Никольское кольцо',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 20,
        isEdited: false,
      },
      {
        uploadedBy: 2,
        title: 'Ученые нашли новый способ лечения диабета 1 типа',
        text: 'Исследователи из Сеченовского университета разработали метод лечения диабета 1 типа с использованием стволовых клеток. Технология позволяет восстанавливать бета-клетки поджелудочной железы, отвечающие за выработку инсулина. Клинические испытания начнутся в конце 2026 года.',
        category: 'health',
        type: 'text',
        source: 'Доктор Живаго',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 25,
        isEdited: false,
      },
      {
        uploadedBy: 3,
        title: 'В Москве открылся международный кинофестиваль',
        text: '43-й Московский международный кинофестиваль открылся премьерой нового фильма Никиты Михалкова. В конкурсной программе участвуют 15 картин из России, Франции, Китая и Ирана. Специальным гостем фестиваля стал Квентин Тарантино, который представит ретроспективу своих фильмов.',
        category: 'culture',
        type: 'image',
        source: 'Культурная столица',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 30,
        isEdited: false,
      },
      {
        uploadedBy: 15,
        title: 'Новый закон о налогах и сборах',
        text: 'Президент России подписал закон о налогах и сборах. Закон вступит в силу с 1 января 2026 года. Закон предусматривает новые налоги и сборы для физических и юридических лиц. Закон также предусматривает новые льготы для малого и среднего бизнеса.',
        category: 'economy',
        type: 'text',
        source: 'Экономический обозреватель',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 35,
        isEdited: false,
      },
      {
        uploadedBy: 16,
        title: 'Новый закон о здравоохранении',
        text: 'Президент России подписал закон о здравоохранении. Закон вступит в силу с 1 января 2026 года. Закон предусматривает новые правила для медицинских учреждений. Закон также предусматривает новые льготы для медицинских работников.',
        category: 'health',
        type: 'image',
        source: 'Здравоохранение',
        newsUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        viewsCount: 35,
        isEdited: false,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('News', null, {});
  },
};
