/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Users', [
      {
        nickname: 'alex_92',
        name: 'Алексей Иванов',
        age: 30,
        email: 'alex@example.com',
        address: 'Москва, ул. Ленина, 10',
        job: 'Frontend разработчик',
        status: 'В поиске новых вызовов',
        phone: '+79161234567',
        avatarUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'maria_joy',
        name: 'Мария Петрова',
        age: 25,
        email: 'maria@example.com',
        address: 'Санкт-Петербург, Невский пр., 25',
        job: 'Дизайнер UI/UX',
        status: 'Люблю создавать красивые интерфейсы',
        phone: '+79167654321',
        avatarUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'tech_guru',
        name: 'Дмитрий Сидоров',
        age: 35,
        email: 'dmitry@example.com',
        address: 'Казань, ул. Баумана, 15',
        job: 'Backend разработчик',
        status: 'Пишу на Node.js и Python',
        phone: '+79165557788',
        avatarUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'ivan_petrov',
        name: 'Иван Петров',
        age: 33,
        email: 'ivan.petrov@mail.ru',
        address: 'Москва, ул. Кутузова, 12',
        job: 'Каменщик',
        status: 'Работа выполнена в срок',
        phone: '+79536788832',
        avatarUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'mariya_sid',
        name: 'Вероника Сидорова',
        age: 28,
        email: 'mariya.sidorova@gmail.com',
        address: 'Санкт-Петербург, Невский проспект, 67',
        job: 'Фотограф',
        status: 'Наблюдаю за полетами майских жуков',
        phone: '+79112345678',
        avatarUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
        visibility: 'public',
        passwordHash: 123,
      },

      {
        nickname: 'sergey_pro',
        name: 'Сергей Прохоров',
        age: 35,
        email: 'aleksey.ivanov@yandex.ru',
        address: 'Новосибирск, Площадь Гарина-Михайловского, 45',
        job: 'Водитель',
        status: 'Пробили колеса в машине сволочи!',
        phone: '+79134567890',
        avatarUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'ekaterina_kuz',
        name: 'Екатерина Кузнецова',
        age: 29,
        email: 'ekaterina.kuznetsova@bk.ru',
        address: 'Екатеринбург, Площадь 1905 года, 89',
        job: 'Дизайнер',
        status: 'Кто уже купался в этом году?',
        phone: '+79123456789',
        avatarUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'jovinco',
        name: 'Олег Малахов',
        age: 38,
        email: 'malahov.1987@mail.ru',
        address: 'Смоленск, пр-т Строителей, 1/42',
        job: 'Frontend разработчик',
        status: 'В поиске новых вызовов',
        phone: '+79156548842',
        avatarUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'dmitriy_smir',
        name: 'Андрей Смирнов',
        age: 31,
        email: 'dmitriy.smirnov@inbox.ru',
        address: 'Казань, пл. Кремлёвская, 72',
        job: 'Барбер',
        status: 'В поисках счастья..',
        phone: '+79876543210',
        avatarUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'anna_mac',
        name: 'Анна Макарова',
        age: 24,
        email: 'anya.makarova@gmail.com',
        address: 'Сочи, мкр-н Адлер, ул. Абрикосовая, 55',
        job: 'Администратор',
        status: 'Скоро выхожу замуж! Ура!',
        phone: '+79164557698',
        avatarUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'sofia_f',
        name: 'Софья Филимонова',
        age: 36,
        email: 'sofia_fill@gmail.com',
        address: 'Смоленск, ул. Румянцева, 64',
        job: 'Домохозяйка',
        status: 'В активном поиске',
        phone: '+79159853221',
        avatarUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'artem_v',
        name: 'Артём Волков',
        age: 30,
        email: 'artem.volkov@yandex.ru',
        address: 'Ростов-на-Дону, ул. Ленина, 112',
        job: 'Программист',
        status: 'Пью кофе и кодю',
        phone: '+79195678901',
        avatarUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'elena_n',
        name: 'Елена Новикова',
        age: 27,
        email: 'elena.novikova@mail.ru',
        address: 'Уфа, ул. Гоголя, 33',
        job: 'Повар',
        status: 'Пишу книгу о кулинарии',
        phone: '+79102345678',
        avatarUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'igor_k',
        name: 'Игорь Ковалёв',
        age: 34,
        email: 'igor.kovalyov@inbox.ru',
        address: 'Пермь, ул. Ленина, 44',
        job: 'Строитель',
        status: 'На отдыхе в горах',
        phone: '+79178901234',
        avatarUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'vera_m',
        name: 'Вера Морозова',
        age: 26,
        email: 'vera.morozova@gmail.com',
        address: 'Чита, ул. Советская, 22',
        job: 'Юрист',
        status: 'Свободна для работы',
        phone: '+79187890123',
        avatarUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'alexandra_b',
        name: 'Александра Белова',
        age: 25,
        email: 'alexandra.belova@bk.ru',
        address: 'Тула, ул. Пушкина, 77',
        job: 'Модель',
        status: 'Снимаю ролики для TikTok',
        phone: '+79145678901',
        avatarUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'mikhail_y',
        name: 'Михаил Яковлев',
        age: 32,
        email: 'mikhail.yakovlev@yandex.ru',
        address: 'Краснодар, ул. Ленина, 88',
        job: 'Преподаватель',
        status: 'Изучаю новые языки программирования',
        phone: '+79135567890',
        avatarUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
      {
        nickname: 'anastasia_s',
        name: 'Анастасия Соколова',
        age: 23,
        email: 'anastasia.sokolova@gmail.com',
        address: 'Владивосток, ул. Ленина, 55',
        job: 'Медицинская сестра',
        status: 'Сегодня день рождения!',
        phone: '+79123756789',
        avatarUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
        visibility: 'public',
        passwordHash: 123,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
