/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Posts', [
      {
        userId: 1,
        text: 'Сегодня завершил большой проект! Очень доволен результатом. #успех #работа',
        postUrl: '/default-image.jpg',
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 2,
        text: 'Ищу вдохновение для нового дизайна. Какие тренды в UI сейчас актуальны?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 3,
        text: 'Поделюсь кодом оптимизации запросов к PostgreSQL...',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 4,
        text: '- Выучить JS ? - Да легко! Можете меня поздравить, это было нечто. Это почти как пройти афганскую войну.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 5,
        text: 'Ссыку на материалы прилагаю https://doka.guide не благодарите.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 6,
        text: 'Это мой приватный пост, который вижу только я и никто другой.',
        postUrl: '/default-image.jpg',
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 7,
        text: 'Обучающее видео - как я выучил JavaScript за 10 минут.',
        postUrl: '/default-video.mp4',
        previewUrl: '/default-preview.mp4',
        thumbnailUrl: '/default-thumbnail.jpg',
        isPublic: true,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 8,
        text: 'Красивое фото из Грузии.',
        postUrl: '/default-image.jpg',
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 9,
        text: 'Мое первое фото',
        postUrl: '/default-image.jpg',
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 10,
        text: 'Поздравьте меня с днем рождения! Сегодня отличная погода - как мне повезло!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 11,
        text: 'Я выучила React и устроилась на работу. Теперь я работаю 24/7. Это приватный пост',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 12,
        text: 'Ссылка на интересный ресурс https://doka.guide/js',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 13,
        text: 'Видео с уроком',
        postUrl: '/default-video.mp4',
        previewUrl: '/default-preview.mp4',
        thumbnailUrl: '/default-thumbnail.jpg',
        isPublic: true,
        type: 'video',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 14,
        text: 'Фото из путешествия',
        postUrl: '/default-image.jpg',
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'image',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 15,
        text: 'Ребята продаю машину в отличном состоянии.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },

      {
        userId: 16,
        text: 'Ребята, копируйте ссылку пока не пропала https://doka.guide/js/expressions-vs-statements',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 17,
        text: 'Сегодня Redux Toolkit! Жду поздравлений.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 18,
        text: 'Когда же это уже все закончится? Программисты?!.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 1,
        text: 'Какой сегодня чудесный день!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 2,
        text: 'Какой сериал посоветуете посмотреть? Что последнее Вам понравилось?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 3,
        text: 'Поздравляю всех с началом лета, оно будет прекрасным.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 4,
        text: 'Поздравляю Вас с прошедшими майскими праздникам, всем добра и мира!',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 5,
        text: 'Скоро отпуск! Ура! Уже взяли билеты в Сочи, Красная Поляна ждет нас.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 6,
        text: 'Пора бы уже и мне найти работу. Ребята как у Вас сейчас дела с работой, долго искали?',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 7,
        text: 'Сегодня освоен React Router. Завтра начну Redux и так выучу React.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 8,
        text: 'Скоро экзамен по истории России, пожелайте мне удачи!.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: false,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
      {
        userId: 9,
        text: 'Учимся программировать. Подписываемся на мой канал в YouTube и Telegram! Ссылку оставлю в комментариях.',
        postUrl: null,
        previewUrl: null,
        thumbnailUrl: null,
        isPublic: true,
        type: 'text',
        pinned: false,
        isEdited: false,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Posts', null, {});
  },
};
