/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Users', [
      {
        nickname: 'alex_92',
        name: 'Алексей Иванов',
        birthDate: '1992-01-01',
        email: 'alex@example.com',
        address: 'Москва, ул. Ленина, 10',
        job: 'Frontend разработчик',
        status: 'В поиске новых вызовов',
        phone: '+7 (916) 123-45-67',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'maria_joy',
        name: 'Мария Петрова',
        birthDate: '1997-05-15',
        email: 'maria@example.com',
        address: 'Санкт-Петербург, Невский пр., 25',
        job: 'Дизайнер UI/UX',
        status: 'Люблю создавать красивые интерфейсы',
        phone: '+7 (916) 765-43-21',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'tech_guru',
        name: 'Дмитрий Сидоров',
        birthDate: '1987-11-20',
        email: 'dmitry@example.com',
        address: 'Казань, ул. Баумана, 15',
        job: 'Backend разработчик',
        status: 'Пишу на Node.js и Python',
        phone: '+7 (916) 555-77-88',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'ivan_petrov',
        name: 'Иван Петров',
        birthDate: '1989-03-10',
        email: 'ivan.petrov@mail.ru',
        address: 'Москва, ул. Кутузова, 12',
        job: 'Каменщик',
        status: 'Работа выполнена в срок',
        phone: '+7 (953) 678-88-32',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'mariya_sid',
        name: 'Вероника Сидорова',
        birthDate: '1994-07-25',
        email: 'mariya.sidorova@gmail.com',
        address: 'Санкт-Петербург, Невский проспект, 67',
        job: 'Фотограф',
        status: 'Наблюдаю за полетами майских жуков',
        phone: '+7 (911) 234-56-78',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },

      {
        nickname: 'sergey_pro',
        name: 'Сергей Прохоров',
        birthDate: '1987-11-20',
        email: 'aleksey.ivanov@yandex.ru',
        address: 'Новосибирск, Площадь Гарина-Михайловского, 45',
        job: 'Водитель',
        status: 'Пробили колеса в машине сволочи!',
        phone: '+7 (913) 456-78-90',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'ekaterina_kuz',
        name: 'Екатерина Кузнецова',
        birthDate: '1993-04-12',
        email: 'ekaterina.kuznetsova@bk.ru',
        address: 'Екатеринбург, Площадь 1905 года, 89',
        job: 'Дизайнер',
        status: 'Кто уже купался в этом году?',
        phone: '+7 (912) 345-67-89',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'jovinco',
        name: 'Олег Малахов',
        birthDate: '1987-06-15',
        email: 'malahov.1987@mail.ru',
        address: 'Смоленск, пр-т Строителей, 1/42',
        job: 'Frontend разработчик',
        status: 'В поиске новых вызовов',
        phone: '+7 (915) 654-88-42',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'dmitriy_smir',
        name: 'Андрей Смирнов',
        birthDate: '1991-06-18',
        email: 'dmitriy.smirnov@inbox.ru',
        address: 'Казань, пл. Кремлёвская, 72',
        job: 'Барбер',
        status: 'В поисках счастья..',
        phone: '+7 (987) 654-32-10',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'anna_mac',
        name: 'Анна Макарова',
        birthDate: '1998-09-22',
        email: 'anya.makarova@gmail.com',
        address: 'Сочи, мкр-н Адлер, ул. Абрикосовая, 55',
        job: 'Администратор',
        status: 'Скоро выхожу замуж! Ура!',
        phone: '+7 (916) 455-76-98',
        avatarUrl: '/default-user.png',
        isPublic: false,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'sofia_f',
        name: 'Софья Филимонова',
        birthDate: '1986-03-08',
        email: 'sofia_fill@gmail.com',
        address: 'Смоленск, ул. Румянцева, 64',
        job: 'Домохозяйка',
        status: 'В активном поиске',
        phone: '+7 (915) 985-32-21',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'artem_v',
        name: 'Артём Волков',
        birthDate: '1992-07-15',
        email: 'artem.volkov@yandex.ru',
        address: 'Ростов-на-Дону, ул. Ленина, 112',
        job: 'Программист',
        status: 'Пью кофе и кодю',
        phone: '+7 (919) 567-89-01',
        avatarUrl: '/default-user.png',
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'elena_n',
        name: 'Елена Новикова',
        birthDate: '1995-01-01',
        email: 'elena.novikova@mail.ru',
        address: 'Уфа, ул. Гоголя, 33',
        job: 'Повар',
        status: 'Пишу книгу о кулинарии',
        phone: '+7 (910) 234-56-78',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'igor_k',
        name: 'Игорь Ковалёв',
        birthDate: '1990-05-05',
        email: 'igor.kovalyov@inbox.ru',
        address: 'Пермь, ул. Ленина, 44',
        job: 'Строитель',
        status: 'На отдыхе в горах',
        phone: '+7 (917) 890-12-34',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'vera_m',
        name: 'Вера Морозова',
        birthDate: '1996-03-15',
        email: 'vera.morozova@gmail.com',
        address: 'Чита, ул. Советская, 22',
        job: 'Юрист',
        status: 'Свободна для работы',
        phone: '+7 (918) 789-01-23',
        avatarUrl: '/default-user.png',
        isPublic: false,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'alexandra_b',
        name: 'Александра Белова',
        birthDate: '1997-07-20',
        email: 'alexandra.belova@bk.ru',
        address: 'Тула, ул. Пушкина, 77',
        job: 'Модель',
        status: 'Снимаю ролики для TikTok',
        phone: '+7 (914) 567-89-01',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
      {
        nickname: 'mikhail_y',
        name: 'Михаил Яковлев',
        birthDate: '1988-11-10',
        email: 'mikhail.yakovlev@yandex.ru',
        address: 'Краснодар, ул. Ленина, 88',
        job: 'Преподаватель',
        status: 'Изучаю новые языки программирования',
        phone: '+7 (913) 556-78-90',
        avatarUrl: '/default-user.png',
        isPublic: false,
        gender: 'male',
        passwordHash: 123,
      },
      {
        nickname: 'anastasia_s',
        name: 'Анастасия Соколова',
        birthDate: '1999-04-05',
        email: 'anastasia.sokolova@gmail.com',
        address: 'Владивосток, ул. Ленина, 55',
        job: 'Медицинская сестра',
        status: 'Сегодня день рождения!',
        phone: '+7 (912) 375-67-89',
        avatarUrl: '/default-user.png',
        isPublic: true,
        gender: 'female',
        passwordHash: 123,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
