/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Music', [
      {
        uploadedBy: 1,
        title: 'Radioactive',
        artist: 'Imagine Dragons',
        album: 'Night Visions',
        year: 2012,
        duration: 186,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'rock',
        description: 'Хит из альбома Night Visions',
        isPublic: true,
        playsCount: 100,
      },
      {
        uploadedBy: 2,
        title: 'Bad guy',
        artist: 'Billie Eilish',
        album: 'When We All Fall Asleep',
        year: 2019,
        duration: 194,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'pop',
        description: 'Грэмми-победитель 2020 года',
        isPublic: true,
        playsCount: 50,
      },
      {
        uploadedBy: 3,
        title: 'Bohemian Rhapsody',
        artist: 'Queen',
        album: 'A Night at the Opera',
        year: 1975,
        duration: 355,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'rock',
        description: 'Легендарная песня',
        isPublic: true,
        playsCount: 60,
      },
      {
        uploadedBy: 4,
        title: 'Imagine',
        artist: 'John Lennon',
        album: 'Imagine',
        year: 1971,
        duration: 185,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'pop',
        description: 'Философская баллада о мире и гармонии',
        isPublic: false,
        playsCount: 70,
      },
      {
        uploadedBy: 5,
        title: 'Take Five',
        artist: 'Dave Brubeck Quartet',
        album: 'Time Out',
        year: 1959,
        duration: 323,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'jazz',
        description: 'Инструментальный джазовый шедевр в размере 5/4',
        isPublic: true,
        playsCount: 50,
      },
      {
        uploadedBy: 6,
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        duration: 330,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'pop',
        description: 'Иконический трек короля поп-музыки',
        isPublic: true,
        playsCount: 80,
      },
      {
        uploadedBy: 7,
        title: 'Smells Like Teen Spirit',
        artist: 'Nirvana',
        album: 'Nevermind',
        year: 1991,
        duration: 302,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'rock',
        description: 'Гимн поколения 90-х',
        isPublic: false,
        playsCount: 90,
      },
      {
        uploadedBy: 8,
        title: 'Clair de Lune',
        artist: 'Claude Debussy',
        album: 'Suite bergamasque',
        year: 1905,
        duration: 247,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'classical',
        description: 'Вечная классика французского импрессионизма',
        isPublic: true,
        playsCount: 55,
      },
      {
        uploadedBy: 9,
        title: 'Lose Yourself',
        artist: 'Eminem',
        album: '8 Mile Soundtrack',
        year: 2002,
        duration: 283,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'hip-hop',
        description: 'Мотивирующий трек из фильма 8 Миль',
        isPublic: true,
        playsCount: 65,
      },
      {
        uploadedBy: 10,
        title: 'Stairway to Heaven',
        artist: 'Led Zeppelin',
        album: 'Led Zeppelin IV',
        year: 1971,
        duration: 654,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'rock',
        description: 'Эпическая рок-баллада с культовым гитарным соло',
        isPublic: false,
        playsCount: 75,
      },
      {
        uploadedBy: 11,
        title: 'Blinding Lights',
        artist: 'The Weeknd',
        album: 'After Hours',
        year: 2020,
        duration: 198,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'pop',
        description: 'Ретро-синтпоп хит с ностальгическим звучанием 80-х',
        isPublic: true,
        playsCount: 85,
      },
      {
        uploadedBy: 12,
        title: 'Hotel California',
        artist: 'Eagles',
        album: 'Hotel California',
        year: 1976,
        duration: 376,
        audioUrl: '/default-audio.mp3',
        coverUrl: '/default-image.jpg',
        category: 'rock',
        description: 'Легендарная песня о калифорнийской мечте',
        isPublic: true,
        playsCount: 95,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Music', null, {});
  },
};
