import { createSlice } from '@reduxjs/toolkit';

const usersSlice = createSlice({
  name: 'users',
  initialState: {
    usersData: [
      {
        id: 1,
        nickname: 'ivan_petrov',
        name: 'Иван Петров',
        age: 33,
        email: 'ivan.petrov@mail.ru',
        address: 'Москва, ул. Кутузова, 12',
        job: 'Каменщик',
        status: 'Работа выполнена в срок',
        phone: '+7-953-678-88-32',
        photoUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
      },
      {
        id: 2,
        nickname: 'mariya_sid',
        name: 'Мария Сидорова',
        age: 28,
        email: 'mariya.sidorova@gmail.com',
        address: 'Санкт-Петербург, Невский проспект, 67',
        job: 'Фотограф',
        status: 'Наблюдаю за полетами майских жуков',
        phone: '+7-911-234-56-78',
        photoUrl: 'https://randomuser.me/api/portraits/women/31.jpg',
      },

      {
        id: 3,
        nickname: 'aleksey_ivan',
        name: 'Алексей Иванов',
        age: 35,
        email: 'aleksey.ivanov@yandex.ru',
        address: 'Новосибирск, Площадь Гарина-Михайловского, 45',
        job: 'Водитель',
        status: 'Пробили колеса в машине сволочи!',
        phone: '+7-913-456-78-90',
        photoUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
      },
      {
        id: 4,
        nickname: 'ekaterina_kuz',
        name: 'Екатерина Кузнецова',
        age: 29,
        email: 'ekaterina.kuznetsova@bk.ru',
        address: 'Екатеринбург, Площадь 1905 года, 89',
        job: 'Дизайнер',
        status: 'Кто уже купался в этом году?',
        phone: '+7-912-345-67-89',
        photoUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
      },
      {
        id: 5,
        nickname: 'dmitriy_smir',
        name: 'Дмитрий Смирнов',
        age: 31,
        email: 'dmitriy.smirnov@inbox.ru',
        address: 'Казань, пл. Кремлёвская, 72',
        job: 'Барбер',
        status: 'В поисках счастья..',
        phone: '+7-987-654-32-10',
        photoUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
      },
      {
        id: 6,
        nickname: 'anna_mac',
        name: 'Анна Макарова',
        age: 24,
        email: 'anya.makarova@gmail.com',
        address: 'Сочи, мкр-н Адлер, ул. Абрикосовая, 55',
        job: 'Администратор',
        status: 'Скоро выхожу замуж! Ура!',
        phone: '+7-916-455-76-98',
        photoUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
      },
      {
        id: 7,
        nickname: 'sofia_f',
        name: 'Софья Филимонова',
        age: 36,
        email: 'sofia_fill@gmail.com',
        address: 'Смоленск, ул. Румянцева, 64',
        job: 'Домохозяйка',
        status: 'В активном поиске',
        phone: '+7-915-985-32-21',
        photoUrl: 'https://randomuser.me/api/portraits/women/67.jpg',
      },
      {
        id: 9,
        nickname: 'artem_v',
        name: 'Артём Волков',
        age: 30,
        email: 'artem.volkov@yandex.ru',
        address: 'Ростов-на-Дону, ул. Ленина, 112',
        job: 'Программист',
        status: 'Пью кофе и кодю',
        phone: '+7-919-567-89-01',
        photoUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
      },
      {
        id: 10,
        nickname: 'elena_n',
        name: 'Елена Новикова',
        age: 27,
        email: 'elena.novikova@mail.ru',
        address: 'Уфа, ул. Гоголя, 33',
        job: 'Повар',
        status: 'Пишу книгу о кулинарии',
        phone: '+7-910-234-56-78',
        photoUrl: 'https://randomuser.me/api/portraits/women/33.jpg',
      },

      {
        id: 11,
        nickname: 'igor_k',
        name: 'Игорь Ковалёв',
        age: 34,
        email: 'igor.kovalyov@inbox.ru',
        address: 'Пермь, ул. Ленина, 44',
        job: 'Строитель',
        status: 'На отдыхе в горах',
        phone: '+7-917-890-12-34',
        photoUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
      },
      {
        id: 12,
        nickname: 'vera_m',
        name: 'Вера Морозова',
        age: 26,
        email: 'vera.morozova@gmail.com',
        address: 'Чита, ул. Советская, 22',
        job: 'Юрист',
        status: 'Свободна для работы',
        phone: '+7-918-789-01-23',
        photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
      },
      {
        id: 13,
        nickname: 'alexandra_b',
        name: 'Александра Белова',
        age: 25,
        email: 'alexandra.belova@bk.ru',
        address: 'Тула, ул. Пушкина, 77',
        job: 'Модель',
        status: 'Снимаю ролики для TikTok',
        phone: '+7-914-567-89-01',
        photoUrl: 'https://randomuser.me/api/portraits/women/55.jpg',
      },
      {
        id: 14,
        nickname: 'mikhail_y',
        name: 'Михаил Яковлев',
        age: 32,
        email: 'mikhail.yakovlev@yandex.ru',
        address: 'Краснодар, ул. Ленина, 88',
        job: 'Преподаватель',
        status: 'Изучаю новые языки программирования',
        phone: '+7-913-456-78-90',
        photoUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
      },
      {
        id: 15,
        nickname: 'anastasia_s',
        name: 'Анастасия Соколова',
        age: 23,
        email: 'anastasia.sokolova@gmail.com',
        address: 'Владивосток, ул. Ленина, 55',
        job: 'Медицинская сестра',
        status: 'Сегодня день рождения!',
        phone: '+7-912-345-67-89',
        photoUrl: 'https://randomuser.me/api/portraits/women/66.jpg',
      },
    ],
    status: 'idle', // 'idle' | 'loading' | 'succeeded' | 'failed'
    error: null,
  },
  reducers: {
    setUsers: (state, action) => {
      state.usersData = action.payload;
    },
  },
});
export default usersSlice.reducer;
